### ISSUE TITLE
bta be 

### ISSUE THREAD

**Issue by somj57** [prakhar7s/drag-and-drop#1]
bta be ye ky ky ha

**Comment by prakhar7s** [comment]
Its a drag and drop. It has 5 slots for images(can add any number of slots), you can drag the image in any of the slots then the image automatically shifts to that particular slot....
and please use formal language from the next time.😂

**Comment by prakhar7s** [comment]
to know more check this https://prakhar7s.github.io/drag-and-drop.github.io/

**Comment by somj57** [comment]
Hellow
